# Generated by Django 5.2.4 on 2025-07-23 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnimeSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название сезона')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('release_year', models.IntegerField(verbose_name='Год выпуска')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Сезон аниме',
                'verbose_name_plural': 'Сезоны аниме',
                'ordering': ['-release_year'],
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название серии')),
                ('episode_number', models.PositiveIntegerField(verbose_name='Номер серии')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='Видео файл')),
                ('description', models.TextField(blank=True, verbose_name='Описание серии')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='anime.animeseason', verbose_name='Сезон')),
            ],
            options={
                'verbose_name': 'Серия',
                'verbose_name_plural': 'Серии',
                'ordering': ['episode_number'],
            },
        ),
    ]
