# Generated by Django 5.2.4 on 2025-07-23 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя персонажа')),
                ('alias', models.CharField(blank=True, max_length=100, verbose_name='Псевдоним')),
                ('description', models.TextField(verbose_name='Описание')),
                ('backstory', models.TextField(blank=True, verbose_name='Предыстория')),
                ('image', models.ImageField(blank=True, null=True, upload_to='characters/', verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Персонаж',
                'verbose_name_plural': 'Персонажи',
                'ordering': ['name'],
            },
        ),
    ]
