# Generated by Django 5.2.4 on 2025-07-23 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название тома')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Том',
                'verbose_name_plural': 'Тома',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название главы')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='audio/', verbose_name='Аудиофайл')),
                ('illustration', models.ImageField(blank=True, null=True, upload_to='illustrations/', verbose_name='Иллюстрация')),
                ('content', models.TextField(blank=True, verbose_name='Текст главы')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('volume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='novel.volume', verbose_name='Том')),
            ],
            options={
                'verbose_name': 'Глава',
                'verbose_name_plural': 'Главы',
                'ordering': ['order'],
            },
        ),
    ]
